-- AgroAI application schema for Supabase/PostgreSQL.
-- Run this once in Supabase Dashboard -> SQL Editor.

create table if not exists public.users (
    id bigint generated by default as identity primary key,
    username varchar(255) not null,
    email varchar(255) not null unique,
    password varchar(255) not null,
    role varchar(50) not null default 'farmer',
    phone varchar(50),
    location varchar(255),
    state varchar(255),
    farm_size numeric,
    language varchar(100),
    created_at timestamptz not null default now()
);

create table if not exists public.crops (
    id bigint generated by default as identity primary key,
    user_id bigint references public.users(id) on delete set null,
    name varchar(255) not null,
    n integer,
    p integer,
    k integer,
    ph real,
    temperature real,
    humidity real,
    rainfall real,
    prediction varchar(255),
    created_at timestamptz not null default now()
);

create table if not exists public.diseases (
    id bigint generated by default as identity primary key,
    name varchar(255) not null unique,
    severity varchar(100),
    cause text,
    chemical_cure text,
    organic_cure text
);

create table if not exists public.disease_reports (
    id bigint generated by default as identity primary key,
    user_id bigint references public.users(id) on delete set null,
    crop_name varchar(255),
    disease_name varchar(255),
    severity varchar(100),
    image_path varchar(255),
    status varchar(100) not null default 'pending',
    created_at timestamptz not null default now()
);

create table if not exists public.equipment (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    type varchar(255),
    owner varchar(255),
    rate_per_hour numeric,
    rate_per_day numeric,
    location varchar(255),
    phone varchar(50),
    image_url text,
    availability boolean not null default true
);

create table if not exists public.bookings (
    id bigint generated by default as identity primary key,
    user_id bigint references public.users(id) on delete set null,
    equipment_id bigint references public.equipment(id) on delete set null,
    hours integer,
    total_cost numeric,
    status varchar(100) not null default 'pending',
    date varchar(100),
    created_at timestamptz not null default now()
);

create table if not exists public.products (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    description text,
    price numeric,
    category varchar(255),
    image_url text,
    stock integer not null default 10
);

create table if not exists public.listings (
    id bigint generated by default as identity primary key,
    user_id bigint references public.users(id) on delete set null,
    category varchar(255) not null,
    title varchar(255) not null,
    description text,
    price numeric not null,
    unit varchar(100) not null default 'quintal',
    location varchar(255) not null,
    quantity varchar(255) not null,
    phone varchar(50) not null,
    created_at timestamptz not null default now()
);

create table if not exists public.orders (
    id bigint generated by default as identity primary key,
    user_id bigint references public.users(id) on delete set null,
    product_id bigint references public.products(id) on delete set null,
    quantity integer,
    total_cost numeric,
    status varchar(100) not null default 'pending',
    address text,
    created_at timestamptz not null default now()
);

create table if not exists public.market_prices (
    id bigint generated by default as identity primary key,
    crop_name varchar(255) not null,
    market_name varchar(255) not null,
    state varchar(255) not null,
    current_price numeric,
    predicted_price numeric,
    date varchar(100)
);

create table if not exists public.notifications (
    id bigint generated by default as identity primary key,
    user_id bigint references public.users(id) on delete set null,
    title varchar(255) not null,
    message text not null,
    severity varchar(100),
    date varchar(100),
    category varchar(100),
    created_at timestamptz not null default now()
);

create table if not exists public.login_attempts (
    id bigint generated by default as identity primary key,
    user_id bigint references public.users(id) on delete set null,
    email varchar(255),
    success boolean,
    created_at timestamptz not null default now()
);

create table if not exists public.login_sessions (
    id bigint generated by default as identity primary key,
    user_id bigint references public.users(id) on delete set null,
    session_token text,
    active boolean not null default true,
    started_at timestamptz not null default now(),
    last_activity_at timestamptz not null default now()
);

create table if not exists public.chat_history (
    id bigint generated by default as identity primary key,
    user_id bigint references public.users(id) on delete set null,
    sender varchar(100),
    message text,
    timestamp timestamptz not null default now()
);

create index if not exists idx_crops_user_id on public.crops(user_id);
create index if not exists idx_disease_reports_user_id on public.disease_reports(user_id);
create index if not exists idx_bookings_user_id on public.bookings(user_id);
create index if not exists idx_bookings_equipment_id on public.bookings(equipment_id);
create index if not exists idx_orders_user_id on public.orders(user_id);
create index if not exists idx_orders_product_id on public.orders(product_id);
create index if not exists idx_listings_user_id on public.listings(user_id);
create index if not exists idx_login_attempts_user_id on public.login_attempts(user_id);
create index if not exists idx_login_sessions_user_id on public.login_sessions(user_id);
create index if not exists idx_market_prices_crop_name on public.market_prices(crop_name);
